### ISSUE TITLE
Programming ADS-B Out

### ISSUE THREAD

**Issue by cjohn98** [junzis/pyModeS#37]
This is all great, you've done a really good job explaining how everything works.

I'm tasked with the job of creating an ADS-B Out for a school project. Any tips or advice for doing what you've done here in reverse?

**Comment by junzis** [comment]
Most of the ADS-B information except CPR position can be reversed easily since they are conversions between decimal and binary reprentation . 

In order to get the CPR working, I would recommend looking at the ICAO Annex 10 - Vol3, for example at: http://antena.fe.uni-lj.si/literatura/Razno/Avionika/modes/CPRencoding.pdf

I am also interested in adding a ADS-B encoder to pyModeS. PR is very welcomed!

**Comment by cjohn98** [comment]
Great thanks for the help! I'll let you know when we've finished and any tips/tricks I can think of.
